all:
	@cd cffi_interfaces; $(MAKE)

CLEAN_DIRS += $(LIDT_ROOT)/src/app/processor/cffi_interface

#-----------------------------------------------------------------------------
include $(LIDT_MAKEDIR)/Makefile.app 